### ISSUE TITLE
Use of SSLv3 prevents use on many systems

### ISSUE THREAD

**Issue by WarheadsSE** [openca/libpki#13]
The use of SSLv3 prevents the use & compilation of libpki on many systems with newer openssl, or openssl configured to disable SSLv3

**Comment by opencrypto** [comment]
Thanks for reporting the issue. Does this mean that you can not compile the library on those systems ? Supporting SSLv3 was there strictly for backward compatibility, but definitely nobody shall use anything less than TLSv1.2 :D We will make a note in the TODO list to accommodate for systems that do not have the SSLv3 support compiled in (at compilation time).

**Comment by opencrypto** [comment]
Fixed in [cd4ab5d](https://github.com/openca/libpki/commit/cd4ab5dd5a9f511c40d6a15291658f254a38369d).
