### ISSUE TITLE
Feature request. Define dighest algorithm at the Virtual Host level

### ISSUE THREAD

**Issue by AndreiBrajnicov** [openca/libpki#15]
Hello.

At the moment it is possible to configure **dighest algorithm** in the ocspd.xml. But this value is applied globally. 
But in case if I want to have a mixture of sha1 and sha2 ocsp servers, I should have 2 separate instances. 

My proposal is to configure **dighest algorithm** per virtual host.

Best regards.

**Comment by AndreiBrajnicov** [comment]
It was supposed to create a new issue for openca-ocspd not for libpki.
Excuse me ladies and gentlemen

**Comment by opencrypto** [comment]
Hi Andrei,

I think that the easiest solution here would be to add a per-ca-config 
option for the hash algorithm to use. It should not be that difficult 
either. Please can you add an issue to the openca-ocspd repository 
directly ?

Thanks,
Max
