### ISSUE TITLE
Build with database backends fails on CentOS 7

### ISSUE THREAD

**Issue by hansenjo** [openca/libpki#43]
Building libpki 0.9.0 on current CentOS 7.6 with mariadb-devel-5.5.60 and postgresql-devel-9.2.24 installed fails with exactly the same error as reported in issue #21: passing argument 1 ... discards qualifiers.

A little digging reveals that several function signatures in the MySQL and PostgreSQL code are missing const qualifiers. Here is a patch that makes the library compile for me:

[libpki-0.9.0-constarg.patch](https://github.com/openca/libpki/files/3388963/libpki-0.9.0-constarg.patch.txt)

**Comment by mrbaseman** [comment]
this has already been addressed on the current master with https://github.com/openca/libpki/commit/b1de315552f55713d28edb3c86e3031c1efa4c3c and https://github.com/openca/libpki/commit/675a4b3cf5db878baede8b116a393e64ec96c180 in pull request #41

**Comment by hansenjo** [comment]
Awesome. I should work with master, not the release tarball ;) Thanks!
