### ISSUE TITLE
Latest version from git build fail

### ISSUE THREAD

**Issue by Pro-pra** [openca/libpki#50]
DEBUG: make[3]: Leaving directory '/builddir/build/BUILD/libpki-290e4975c4519ba2dec39d36755f38e816d01530/src/drivers/openssl'
DEBUG: openssl_hsm.c: In function 'HSM_OPENSSL_sign':
DEBUG: openssl_hsm.c:313:58: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
DEBUG:   313 |  if (!EVP_SignFinal(ctx, out_mem->data, (unsigned int *) &ossl_ret, pkey))
DEBUG:       |                                                          ^~~~~~~~~
DEBUG: compilation terminated due to -Wfatal-errors.
DEBUG: cc1: all warnings being treated as errors

**Comment by Pro-pra** [comment]
remove -Werror -Wfatal-errors help me, its not right

**Comment by opencrypto** [comment]
Superseeded.
