### ISSUE TITLE
remove finger from contrib/libpki.spec.orig

### ISSUE THREAD

**Issue by kto2038** [openca/libpki#63]
Recent OSes (such as RHEL 9) don't have `finger` command.
Please remove `finger` command from `contrib/libpki.spec.orig`.

**Comment by opencrypto** [comment]
Addressed in [0940cd5](https://github.com/openca/libpki/commit/0940cd50ea992b44359c7bdb9562f496b086dd0f)

**Comment by kto2038** [comment]
`whami` should be `whoami`.
